### ISSUE TITLE
connect err: host could not be resolved

### ISSUE THREAD

**Issue by nonly** [pintsized/lua-resty-http#101]
`local httpc = http.new()
local ok,err = httpc:connect("localhost", "80")`

err : localhost could not be resolved (3: Host not found)
conf has included  'resolver 8.8.8.8;' and hostname has been written into "/etc/hosts".

how can I connect a hostname such as "localhost" instead of "127.0.0.1" ?

**Comment by pintsized** [comment]
I'm not sure why you're expected google's DNS resolver to resolve localhost for you?

You might want to review this discussion about using dnsmasq (for example) as a local custom resolver.
