### ISSUE TITLE
How to parse a JSON response?

### ISSUE THREAD

**Issue by ifuyivara** [pintsized/lua-resty-http#102]
Hello,

I'm new to LUA. Is there an easy way to parse the json response from a service?

```
local res, err = httpc:request_uri("http://example.com:8500/v1/kv/players/111111", {
                    method = "GET",
                    headers = {
                    ["Content-Type"] = "application/json",
                    }
                })
```

In this case res.body contains the json response. However when I try to use it is always a string.

Thank you!

**Comment by pintsized** [comment]
OpenResty bundles cjson: https://www.kyne.com.au/~mark/software/lua-cjson-manual.html

```lua
require "cjson"
local data = cjson.decode(res.body)
```

`data` will now be a Lua table translation of the JSON string in your `res.body`.

**Comment by ifuyivara** [comment]
awesome. This is exactly what I needed.

Thank you
