### ISSUE TITLE
httpc:set_timeouts doesn't work

### ISSUE THREAD

**Issue by TOTom** [pintsized/lua-resty-http#115]
this is the error message:
     attempt to call method 'settimeouts' (a nil value)

**Comment by pintsized** [comment]
What versions of ngx_lua or OpenResty are you running? This function was added in ngx_lua `v0.10.7`. It's recommended to upgrade, but if for some reason you can't, then you must call `set_timeout` with an appropriate timeout (if different) before each action. i.e. before you connect, then before you run the request, then before you read the body. `set_timeouts` simply allows you to set these upfront.
