### ISSUE TITLE
"no request ctx found" is reported frequently when qps is high

### ISSUE THREAD

**Issue by icewaver** [pintsized/lua-resty-http#119]
2017/08/10 06:45:55 [error] 31061#0: *53723512 lua entry thread aborted: runtime error: ...-1.11.2.2/nginx//../../../src/lib/resty/http.lua:69: no request ctx found
stack traceback:
coroutine 0:
	[C]: in function 'co_status'
	...-1.11.2.2/nginx//../../../src/lib/resty/http.lua:69: in function 'reader'

**Comment by icewaver** [comment]
I think this might be caused by the lua coroutine thread when reading data from socket.

**Comment by pintsized** [comment]
This is most likely related to where you are using the module. Which phase are you in, for example?
 Can you provide a minimal config example to reproduce?
