### ISSUE TITLE
Copy headers from incoming request

### ISSUE THREAD

**Issue by lfundaro** [pintsized/lua-resty-http#120]
Hi ! 

I'm trying to pass the headers that come from the client request like this:

```
local res, err = httpc:request_uri("https://untitled-qdejn192yo17.runkit.sh", {
     method = "GET",
     headers = ngx.req.get_headers(),
     ssl_verify = false
})
```
`headers = ngx.req.get_headers(),` is not working. I don't see the headers on the incoming request server-side. It works only if I do:

`headers = { ["HeaderFromClient"] = ngx.req.get_headers()["HeaderFromClient"]}`

**Comment by pintsized** [comment]
Hi, yes this should work fine, I suspect there's something odd going on elsewhere making it appear as though it's not working?

See here for an example of forwarding the client request, which definitely works: https://github.com/pintsized/lua-resty-http/blob/master/lib/resty/http.lua#L874-L881

**Comment by lfundaro** [comment]
Thank you. It was a problem on my side. All good ! cheers
