### ISSUE TITLE
got a `attempt to send data on a closed socket` error while spawn a http request

### ISSUE THREAD

**Issue by jiajunhuang** [pintsized/lua-resty-http#122]
Hello, I got the error below while I'm trying to spawn a http request before `proxy_pass`, the code in lua is like:

```lua
    local httpc = http.new()
    httpc:connect("http://127.0.0.1", 8080)
    local res, err = httpc:request({
        path="/query",
        query="domain=" .. domain .. "&url=" .. url,
    })
    -- ...
```

and `nginx.conf`:

```
access_by_lua_file /the/path/to/call/the/given/function
```
error:

```
2017/09/04 15:56:03 [error] 6396#6396: *2 attempt to send data on a closed socket: u:0000000041741C00, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost"
```

I'm confused about the error log. Could you please tell me why does it appear?(because I've not set connection pool, it's a brand new connection, right?)

**Comment by hamishforbes** [comment]
You're trying to connect to a *host* of `http://127.0.0.1`, please check the docs and the examples properly first: https://github.com/pintsized/lua-resty-http#connect

You should also be handling the return values from the `httpc:connect()` call to make sure you've actually connected and logging errors if neccessary.

**Comment by jiajunhuang** [comment]
I've spawn a HTTP server listen on 127.0.0.1:8080
