### ISSUE TITLE
could not be resolved (3: Host not found)

### ISSUE THREAD

**Issue by Macrame** [pintsized/lua-resty-http#124]
Thanks for your library first. 
I know that someone reported this "issue" which was not an issue in fact. Today, I tried to resolve this problem but failed.
I had deployed two _service_ in kubernetes.  One is named weedfs-master and another is named feedfs-volume. Those two pod were built from [seaweedfs](https://github.com/chrislusf/seaweedfs). I also built an image based centos 7 and installing **openresty** and **GraphicsMagick**. Let's call it file-server app.
In the file-server, I write upload.lua to handle the file posted by users.
```
function process_upload()
  local weed_master_url = ngx.var.weed_master
  local http = require "resty.http"
  local hc = http.new()
  hc:set_timeout(3000)
  local res, err = hc:request_uri(
    weed_master_url,
    {
      method = 'GET',
      path = '/dir/assign',
      headers = {
        ["Content-Type"] = "application/json"
      }

    })
  if not res then
    ngx.say("failed to request:", err, "<br/>")
    return
  end
  local code = res.status
  ......
end
```
The variable **weed_master** was set to "http://weedfs-master:9333".
I have specified the resolver to 10.0.6.200 in nginx.conf:
```
http {
    ...
    lua_package_path "/usr/local/openresty/lualib/?.lua;;";
    resolver 10.0.6.200;
    server {
        listen       80;
        ...
        location /upload {
          resolver 10.0.6.200;
          default_type "application/json";
          content_by_lua_file conf/upload.lua;
        }
        ...
    }
}
```
Kubernetes provide a component named [kube-dns](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns) which can be used as a DNS server to resolve all the _service_ in the kubernetes cluster. I can see weedfs-master was resolve correctly.

```
#nslookup weedfs-master
Server:		10.0.6.200
Address:	10.0.6.200#53

Name:	weedfs-master.xxxxxx.svc.cluster.local
Address: 10.0.6.102
```

But the hostname could not be resolved  in the lua script: **failed to request:weedfs-master could not be resolved (3: Host not found)<br/>**.
It worked if I set **weed_master** to "http://10.0.6.102:9333".
Would you like to help me about this error? Thank a lot.

**Comment by SeanRobb** [comment]
I am seeing the same problem within kubernetes leveraging kube-dns for resolving.  Any new information on this issue?

**Comment by hamishforbes** [comment]
This library doesn't do anything with DNS itself, it relies on the ngx_lua resolver functionality as documented here: https://github.com/openresty/lua-nginx-module#tcpsockconnect

It sounds like an environment / configuration issue rather than a bug in that but more appropriate for the ngx_lua repo than here.
