### ISSUE TITLE
Can't pass ngx.var.SOME_ VAR(or ngx.req.get_uri_args()) to request_uri()

### ISSUE THREAD

**Issue by CloudWarGit** [pintsized/lua-resty-http#125]
I got a _url_ which was passed by ngx.req.get_uri_args(), and then pass it to http.request_uri method, but the response is always nil. The codes like this:
`local args = ngx.req.get_uri_args()`
`local url = args.url`
`local http = require("resty.http")`
`local httpc = http.new()`
`local res, err = httpc:request_uri(url)`
Then the res is always nil, it seem the httpc:request_uri can't accept the variables
 from nginx.

**Comment by hamishforbes** [comment]
Perhaps you should try logging some of these variables to confirm what they are before passing them into `request_uri()`?

You should also log, or otherwise handle, the value of `err` from the `request_uri()` call for more information.

You certainly *can* pass valid URs from `ngx.var.*` and `ngx.req.get_uri_args` into `request_uri`.
They are simply strings.   
You haven't provided enough information for anyone to possibly help you out here.

**Comment by CloudWarGit** [comment]
@hamishforbes , sorry for unclear descriptions.
At the first, I didn't receive any err from response but a nil. And then I put some probes into the source code of `lua-resty-http/lib/resty/http.lua` to find where is the issue.

 I found the url has been parsed correctly in` request_uri()`, and the request also been sent( `self.send_request()`  return 1 ), but the client didn't receive the response from the destination url, seem the sock was closed before it receiving the response. The following is the probe which i put into function `_M.read_response` (about line 669 in http.lua):

`if not status then`
`        status, version, reason, err = _receive_status(sock)`
`        ngx.log(ngx.ERR,"@@@",status,"@@@",version,"@@@",reson,"@@@",err,"@@@")`
`        if not status then`
`            return nil, err`
`        end`
`    end`

And the another probe in `local function _receive_status`:
`local function _receive_status(sock)`
`    local line, err = sock:receive("*l")`
`    ngx.log(ngx.ERR,"$$$$",line,"\n",err)`
`    if not line then`
`        return nil, nil, nil, err`
`    end`
`    return tonumber(str_sub(line, 10, 12)), tonumber(str_sub(line, 6, 8)), str_sub(line, 14)`
`end`

These two logs in nginx is `@@@nil@@@nil@@@nil@@@closed@@@` and `$$$$nil \n closed`.

However if i set the `local url = "http://substack.net/images/browserify_logo.png"` in my scripts, it can return normal.

I don't know why the sock was closed before the response return. The only different set with normal response is the url which got from `ngx.var.*`

Thanks for your answer.

**Comment by hamishforbes** [comment]
Sounds more like a transient issue with the server you are sending requests to than anything else.

Do you *always* get a closed socket when using the value from ngx.var.* or just intermittently?

**Comment by CloudWarGit** [comment]
@hamishforbes 
I test 4 different websites by this way to capture 4 images:

- "http://substack.net/images/browserify_logo.png"
Return nil, which got a closed socket, always.

- "http://g1.ykimg.com/0100641F465226B1765D450885128BEAD86A21-69AE-7250-7CB4-2D5B64EAE5CD"
Return nil, always, and:
```
local function _receive_status(sock)
    local line, err = sock:receive("*l")
    ngx.log(ngx.ERR,$$$$,line,"\n",err)
    if not line then
        return nil, nil, nil, err
    end

    return tonumber(str_sub(line, 10, 12)), tonumber(str_sub(line, 6, 8)), str_sub(line, 14)
end
```
Here ngx log out put is "`$$$$<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> \n nil`".

- "http://img06.tooopen.com/products/20170909/tooopen_23825925.jpg"  
Returns normally.

- "http://t2.27270.com/uploads/tu/201704/10174/c19.jpg" 
Returns normally.

To the first two url, if i hard code `local url = ` to their url, it can return normally. This is the most confused to me.

**Comment by hamishforbes** [comment]
Can you post a full self-contained example that shows these behaviours?

I can't see how the source of the URL string could possibly be affecting how the response is read. There must be something else going on.

**Comment by CloudWarGit** [comment]
@hamishforbes sorry for late reply.

This is a my test scenario, so the code is quite simple, i have a script httpc.lua:
```
local zhttp         = require("resty.http")

function http_client(uri, body, timeout)
    local httpc = zhttp.new()

    local parsed_uri, err = httpc:parse_uri(uri, false)
    if not parsed_uri then
        return nil, err
    end

    local scheme, host, port, path, query = unpack(parsed_uri)
  --  if not params.path then params.path = path end
  --  if not params.query then params.query = query end

    timeout = timeout or 30000
    httpc:set_timeout(timeout)

    local res, err_ = httpc:request_uri(uri, {
        version = 1.1,
        body = body,
        headers = {
            ["Content-Type"] = "application/x-www-form-urlencoded",
        }
    })
   if not res then
        return nil, err_
   else
      if res.status == 200 then
                return res.body, err_
           else
                return nil, err_
           end
    end
end

function FromBase64(str64)
    local b64chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
    local temp={}
    for i=1,64 do
        temp[string.sub(b64chars,i,i)] = i
    end
    temp['=']=0
    local str=""
    for i=1,#str64,4 do
        if i>#str64 then
            break
        end
        local data = 0
        local str_count=0
        for j=0,3 do
            local str1=string.sub(str64,i+j,i+j)
            if not temp[str1] then
                return
            end
            if temp[str1] < 1 then
                data = data * 64
            else
                data = data * 64 + temp[str1]-1
                str_count = str_count + 1
            end
        end
        for j=16,0,-8 do
            if str_count > 0 then
                str=str..string.char(math.floor(data/math.pow(2,j)))
                data=math.fmod(data,math.pow(2,j))
                str_count = str_count - 1
            end
        end
    end
    return str
end

local args = ngx.req.get_uri_args()

local url = FromBase64(args.url)
--local url = "http://substack.net/images/browserify_logo.png"
--local url = "http://g1.ykimg.com/0100641F465226B1765D450885128BEAD86A21-69AE-7250-7CB4-2D5B64EAE5CD"

local res,err = http_client(url)

ngx.say(res)
```

In nginx.conf, it's just:
```
location /imgproxy {
    content_by_lua_file lua/httpc.lua;
}
```

**Comment by hamishforbes** [comment]
I can't reproduce this with your code, I just don't see any way at all that it's possible the source of the string is affecting `resty-http` somehow, the issue has to be somewhere else in your environment.

P.S there's a built in base64 decode function in ngx_lua: https://github.com/openresty/lua-nginx-module#ngxdecode_base64

**Comment by CloudWarGit** [comment]
@hamishforbes Thanks. 

My environment is really simple, I run an openresty docker container from docker hub, and added a location block as above in default nginx.conf, and then created a script as above in nginx/lua directory.

I even just used the default index.html in openresty, added a `<img src="/imgproxy?url=aHR0cDovL2cxLnlraW1nLmNvbS8wMTAwNjQxRjQ2NTIyNkIxNzY1RDQ1MDg4NTEyOEJFQUQ4NkEyMS02OUFFLTcyNTAtN0NCNC0yRDVCNjRFQUU1Q0Q="`> in it to test.

Maybe this is an individual cases, i will test on other environment. 

Thanks again.
