### ISSUE TITLE
add method params for proxy function

### ISSUE THREAD

**Issue by TaveMyliuX** [pintsized/lua-resty-http#128]
function _M.proxy_request(self,  method，chunksize)
return self:request{
method = method or ngx_req_get_method(),
path = ngx_re_gsub(ngx_var.uri, "\\s", "%20", "jo") .. ngx_var.is_args .. (ngx_var.query_string or ""),
body = self:get_client_body_reader(chunksize),
headers = ngx_req_get_headers(),
}
end

--- local res, err = httpc:proxy_request(method, chunk)  --modify resty.http/http.lua ,add method parmas;

**Comment by hamishforbes** [comment]
The proxy methods are intended as helpers for *simple* proxying cases.
If you need to proxy with a modified method it's probably best to just do this manually
