### ISSUE TITLE
will use request_pipeline increases performance

### ISSUE THREAD

**Issue by yx621** [pintsized/lua-resty-http#130]
From the document, I saw we can use request_pipeline for requests. I am wandering whether this will increase the performance. While reading from the source code, I found the request_pipeline method is also implemented with the regular send_request, and a loop is used to send each request one at a time. 

Seems it cannot help to improve performance, if it is the case, why bothering to have this method? 

Thanks

**Comment by hamishforbes** [comment]
https://en.wikipedia.org/wiki/HTTP_pipelining

Pipelining is intended to reduce latency when sending many requests.
It's not commonly used though as many intermediaries do not support it well.

It's part of the HTTP spec which is why its included.

**Comment by yx621** [comment]
Thanks for the kindly answer, and turned out the critical point for the real answer located in the code:
```
function _M.request_pipeline(self, requests)
    requests = tbl_copy(requests)  -- Take by value

    for _, params in ipairs(requests) do
        if params.headers and params.headers["Expect"] == "100-continue" then
            return nil, "Cannot pipeline request specifying Expect: 100-continue"
        end

        local res, err = self:send_request(params)
        if not res then
            return res, err
        end
    end
```
In the link you send, the http requests in the pipeline are not executed sequentially (I mean the seconds will be send before the first get response from server). Does the request_pipeline also behave like that? If so, for sure the performance will be improved greatly. However, from what I remembered, the request in resty http will be executed synchronously and the response should be received before the following one will be sent out. 

THanks

**Comment by yx621** [comment]
by the way, can you help to re-open this thread? @hamishforbes

**Comment by hamishforbes** [comment]
https://github.com/pintsized/lua-resty-http/blob/master/lib/resty/http.lua#L767

The table of requests is sent off before reading any responses.

**Comment by yx621** [comment]
You are right, thanks! So this method can really reduce the request latency when "overlap" their requests. Very impressive!
