### ISSUE TITLE
lua-resty-http

### ISSUE THREAD

**Issue by NithishReddy** [pintsized/lua-resty-http#131]
I am using lua-resty-http module.

In nginx.conf:

Server {

lua_package_path "/usr/local/ngx_openresty-1.5.8.1/build/lua-resty-http/lib/?.lua;;";

 location ~ /abc/ {

        content_by_lua '

      local http = require "resty.http"
      local httpc = http.new()
      local res, err = httpc:request_uri("https://example.com/national/DetailPage/test", {
        method = "POST",
        body = "a=1&b=2",
        headers = {
          ["Content-Type"] = "application/x-www-form-urlencoded",
        }
      })

      if not res then
        ngx.say("failed to request: ", err)
        return
      end

      ngx.status = res.status

      ngx.say(res.body)
    ';
      }

}

Note : https://example.com is development server
content_by_lua code is not executing . can you please help me to get out of this ??

**Comment by hamishforbes** [comment]
It doesn't seem like you're even getting as far as having a problem with resty-http.
I'd suggest you try the general openresty mailing list first: https://groups.google.com/forum/?fromgroups=#!forum/openresty-en

Also thats a very old version of openresty you're running.
Probably try just adding some ngx.log statements to ensure you're actually executing the code you think you are.

**Comment by ww110052181** [comment]
@hamishforbes 
root@8e783b83713b:/usr/local/openresty/lualib# ls
cjson.so  ngx  rds  redis  resty
this is what you have say ngx context?
the work environment is:
what you have seen "root@8e783b83713b:" is   the openresty docker container that i run the command "docker pull openresty/openresty:xenial" form the internet
