### ISSUE TITLE
request fetching wrong connection data after client timeouts

### ISSUE THREAD

**Issue by Prasanna-sr** [pintsized/lua-resty-http#138]
In keepalive mode when request timeouts, the timeout request TCP port get reused after the timeout, although the response is still in flight, so sometimes future request using the same port gets timedout request response.

_Example_
T1 Request1   port123   --->  (Timeouts, which is set at 2 seconds)
(after 2 seconds)
T2 Request2   port123  --->
T3                                 <---- Response1 port123 (response comes back after 2 seconds)
T4                                 <---- Response2 port123

Note: source host and destination (host+port) same for above TCP request.

So Request2 receives Request1 response.

Above can be fixed by closing connection on timeout request, but feel like this should ideally be handled in the library.

**Comment by mikz** [comment]
I believe what you are describing is fixed in https://github.com/pintsized/lua-resty-http/pull/132.
It is missing a test though.

**Comment by hamishforbes** [comment]
Should be fixed now that #132 is merged
