### ISSUE TITLE
How to execute asynchronous requests?

### ISSUE THREAD

**Issue by ouyangruoxue** [pintsized/lua-resty-http#139]
The method here seems to be a synchronous request。

**Comment by hamishforbes** [comment]
Hi, I suggest you familiarise yourself with the processing model in the nginx Lua module: https://github.com/openresty/lua-nginx-module

If you need to make a request thats asynchronous to the rest of the Lua code executing in the current request then you should look at the ngx.thread API: https://github.com/openresty/lua-nginx-module#ngxthreadspawn
