### ISSUE TITLE
functions.lua:20: send_http(): Failed to send data: 803, context: ngx.timer

### ISSUE THREAD

**Issue by shubenkovva** [pintsized/lua-resty-http#146]
Hello.

We are using lua http module from resty project. Sometimes I find errors in error.log of ningx like:
2018/04/16 12:06:45 [error] 22755#22755: *4233651 [lua] functions.lua:19: send_http(): Failed to send data: {"index":{"_id":"..., context: ngx.timer
2018/04/16 12:06:45 [error] 22755#22755: *4233651 [lua] functions.lua:20: send_http(): Failed to send data: 803, context: ngx.timer
2018/04/16 12:06:45 [error] 22755#22755: *4233651 [lua] functions.lua:23: send_http(): Failed to send data to http://5.61.236.167:9200/_bulk, context: ngx.timer

The client send requests perioditectly, it is difficalt to catch what is the reason of it.

**Comment by hamishforbes** [comment]
That error message doesn't appear to have come from this library?
