### ISSUE TITLE
luajit: /usr/local/openresty/lualib/resty/http.lua:4: attempt to index local 'ngx' (a nil value)

### ISSUE THREAD

**Issue by ww110052181** [pintsized/lua-resty-http#150]
when i run test.lua ;like this
luajit test.lua

something happed
./?.lua;/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/openresty/luajit/share/lua/5.1/?.lua;/usr/local/openresty/luajit/share/lua/5.1/?/init.lua;/usr/local/openresty/lualib/?.lua

luajit: /usr/local/openresty/lualib/resty/http.lua:4: attempt to index local 'ngx' (a nil value)

 the nginx.conf
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    lua_package_path "/usr/local/openresty/lualib/?.lua;;";  #lua module 
    lua_package_cpath "/usr/local/openresty/lualib/?.so;;";  #c module   
    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;
    server{
    }
    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}

 in the test.lua
the following code I have add 
package.path = package.path..";/usr/local/openresty/lualib/?.lua"

waiting for your reply 
thx

**Comment by hamishforbes** [comment]
You can't run this module standalone with LuaJIT, only within the the context of ngx_lua.

**Comment by ww110052181** [comment]
@hamishforbes  thx a lot ,but what can i get  the context of ngx_lua
