### ISSUE TITLE
Why is Content-Length stripped like a hop-by-hop header?

### ISSUE THREAD

**Issue by chriskuehl** [pintsized/lua-resty-http#155]
I'm trying to understand the reason behind stripping Content-Length when proxying, similar to how hop-by-hop headers are stripped:
https://github.com/pintsized/lua-resty-http/blob/fe5c10a47cf40440845c140a5d29cd0e0cd0208f/lib/resty/http.lua#L53-L54

I wasn't able to find an answer in the commit history or other issues -- could anyone explain why the header is dropped?

The reason I'm curious is because we're using lua-resty-http to build an HTTP proxy, but we're seeing unexpected results (chunked encoding for all responses, no Content-Length ever). Here's a simple reproduction of the problem we're encountering:

#### nginx config
```nginx
worker_processes 1;

events {
    worker_connections 4096;
}

http {
    server {
        listen 8111;

        location / {
            content_by_lua_block {
                local http = require('resty.http')
                local httpc = http.new()
                httpc:connect('127.0.0.1', 8112)
                local res, err = httpc:proxy_request()
                httpc:proxy_response(res)
            }
        }
    }
}

```

#### `curl` against `localhost:8112` (the non-OpenResty backend)
```
$ curl -so /dev/null -D- http://localhost:8112/100MB.bin
HTTP/1.0 200 OK
Server: SimpleHTTP/0.6 Python/3.6.0
Date: Tue, 28 Aug 2018 01:07:16 GMT
Content-type: application/octet-stream
Content-Length: 104857600
Last-Modified: Tue, 28 Aug 2018 01:04:12 GMT
```

The backend (`python3 -m http.server` in this case) includes the `Content-Length` header.

#### `curl` against `localhost:8111` (the OpenResty server)
```
$ curl -so /dev/null -D- http://localhost:8111/100MB.bin
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Transfer-Encoding: chunked
Connection: keep-alive
Date: Tue, 28 Aug 2018 01:08:32 GMT
Server: SimpleHTTP/0.6 Python/3.6.0
Last-Modified: Tue, 28 Aug 2018 01:04:12 GMT
```

OpenResty doesn't contain `Content-Length` and uses a chunked transfer encoding instead.

If I remove `Content-Length` from the list of hop-by-hop headers to exclude, the response from OpenResty matches what I originally got from the backend. Specifically, I just deleted these two lines (as a test):

```patch
diff --git a/lib/resty/http.lua b/lib/resty/http.lua
index beff869..db9d5c0 100644
--- a/lib/resty/http.lua
+++ b/lib/resty/http.lua
@@ -50,8 +50,6 @@ local HOP_BY_HOP_HEADERS = {
     ["trailers"]            = true,
     ["transfer-encoding"]   = true,
     ["upgrade"]             = true,
-    ["content-length"]      = true, -- Not strictly hop-by-hop, but Nginx will deal
-                                    -- with this (may send chunked for example).
```

I'm not sure I fully understand the implications of using a chunked transfer encoding, but it seems like there are some downsides to **always** using it (e.g. for the 100MB file used as a test, the browser won't know the file size ahead of time, which is useful for large files).

I wonder if it would be better for the proxying function to preserve the `Content-Length` response header (when present in the response from the backend), or if that introduces any problems? I also saw [this mailing list message](https://groups.google.com/forum/#!msg/openresty-en/p6wkjPUu4GE/raPlzNKdH8AJ) which seems to indicate OpenResty will use chunked mode automatically if there's no `Content-Length` and otherwise not.

Thanks for the help!

**Comment by hamishforbes** [comment]
Because we're not actually proxying directly to the downstream client (e.g. browser), we're passing data to nginx which then handles serving to the client.

You can control the behaviour of nginx yourself anyway through options like http://nginx.org/r/chunked_transfer_encoding

**Comment by chriskuehl** [comment]
Thanks a lot for the reply, @hamishforbes! I was mostly wondering if I was missing an edge case or something, but it sounds like it's not a problem to stop dropping that header in our environment.

Being able to turn off chunked encoding via nginx is uesful, though in our case I think it would still be problematic as the `Content-Length` response header is still not sent (presumably because it would require nginx to buffer the entire response in memory to figure out the length?). Sounds like the right solution for our case is to keep chunked encoding on and stop stripping `Content-Length` when we do the "proxying" with lua-resty-http.

Thanks again!
