### ISSUE TITLE
Handling of multi-value Transfer-Encoding header

### ISSUE THREAD

**Issue by Unigoge** [pintsized/lua-resty-http#157]
The full description of the issue could be found over here - https://github.com/openresty/lua-nginx-module/issues/1373

- for some reason, in case of "the same host" responses the "Transfer-Encoding" header looks like this `Transfer-Encoding: chunked, chunked` ("chunked" value gets inserted twice, or - as another possibility, the whole  "Transfer-Encoding" header gets inserted twice);
- regardless of the exact case - the response headers processing creates a table with two values for "Transfer-Encoding" header (instead of single string value);
- which breaks code over here - https://github.com/pintsized/lua-resty-http/blob/fe7341b755193cadf5daac339c2ab47a3c5ac2da/lib/resty/http.lua#L705 
- and then it tries to read chunked response with regular reader (essentially switching it into HTTP 1.0 mode - where it expects the connection to get closed at the end of response) - and gets blocked... 

The fix is simple - need to replace existing line of code (at line 705):
```
        local ok, encoding = pcall(str_lower, res_headers["Transfer-Encoding"])
```
with something like this:
```
        local ok, encoding;
        if res_headers["Transfer-Encoding"] and type(res_headers["Transfer-Encoding"]) == "string" then
            ok, encoding = pcall(str_lower, res_headers["Transfer-Encoding"])
        elseif res_headers["Transfer-Encoding"] and type(res_headers["Transfer-Encoding"]) == "table" then
            ok, encoding = pcall(str_lower, res_headers["Transfer-Encoding"][1])
        end
```

Thanks,
Gene

**Comment by hamishforbes** [comment]
That's pretty weird to have multiple Transfer-Encoding headers, a server is definitely not supposed to double encode a response according to the spec and adding the header a second time sounds broken.

Nevertheless, if it happens in the real world we should probably try and at the very least handle it gracefully.

I've committed a fix and a test for duplicate headers
