### ISSUE TITLE
Underscores in Headers are replaced with 'HYPHEN_'

### ISSUE THREAD

**Issue by jboyter14** [pintsized/lua-resty-http#38]
The release 0.06 breaks request headers for me (previous release was fine).  Everything seems to work fine except when a header name contains an underscore character.  Some kind of string replace happens on the name and all underscores are replaced with 'HYPHEN_'

**Comment by pintsized** [comment]
Hi. Hmm, I can't really see how this is possible. Can you post an example so that I can try to replicate?

**Comment by jboyter14** [comment]
Thank you for your quick response!  Its so bizarre!  I don't see how it was possible either.  I'll try to get an example together soon, but really all you have to do is a HTTP call; in my case it was a PUT.  Supply a header that has an underscore in the name.  For example:  'my_name', when it gets to the server would become 'my_HYPHEN_name'.  I know it doesn't make sense.  I would propose that it is a problem on my side, but the issue started when I upgraded the library and went away when I reverted to the previous version.

**Comment by pintsized** [comment]
Yeah, very odd. I can't replicate it at my end. If you can reduce your environment down to the fewest parts possible and post a gist, that might give us some clues.
