### ISSUE TITLE
Requests fail for SSL protected pages

### ISSUE THREAD

**Issue by erikcw** [pintsized/lua-resty-http#39]
I'm trying to make a request to a REST API that is protected by `https`.   It keeps failing with `20: unable to get local issuer certificate`.

No errors when I access the API view `curl` or a web-browser.

**Comment by hamishforbes** [comment]
By default the `request_uri()` method will attempt to do SSL verification, you'll need to set [lua_ssl_trusted_certificate](https://github.com/openresty/lua-nginx-module#lua_ssl_trusted_certificate) etc. for this to work.
See the docs for [tcpsocksslhandshake](https://github.com/openresty/lua-nginx-module#tcpsocksslhandshake)

Alternatively you can disable ssl verification, but thats not a great idea from a security point of view.
