### ISSUE TITLE
How to fix lua ssl certificate verify error?

### ISSUE THREAD

**Issue by yurevich1** [pintsized/lua-resty-http#42]
If I use
local http = require("resty.http").new()
local res, err = http:request_uri(url, {
    method = method,
    headers = headers,
    body = body
})

without     ssl_verify = false for https, I receive 
lua ssl certificate verify error: (20: unable to get local issuer certificate),
how to setup nginx.conf in a proper way it order to use ssl_verify = true?

**Comment by didip** [comment]
I have this exact problem as well. How to configure the http client to verify hostname when using SSL?

**Comment by yurevich1** [comment]
@didip  I have to found a solution :(

**Comment by hamishforbes** [comment]
This isn't really anything to do with resty-http, you need to configure Openresty / ngx_lua correctly to allow the underlying feature to do ssl verification.
See here: https://github.com/openresty/lua-nginx-module#tcpsocksslhandshake

**Comment by JewelPengin** [comment]
So I've been under the inclination to use the following https://github.com/openresty/lua-nginx-module#lua_ssl_trusted_certificate. That being said, I have yet to make it work out of the box as well. I get the same message as mentioned above.

**Comment by hamishforbes** [comment]
Yep, you need to set lua_ssl_trusted_certificate to a file containing CA root certs.
For example on RedHat systems the system provided CA certs are at /etc/pki/tls/cert.pem 

You might also need to increase lua_ssl_verify_depth beyond its default of 1.

**Comment by steve-chavez** [comment]
Managed to sort this out in `openresty/openresty:jessie` docker container by doing:
```bash
## In Dockerfile
RUN cp /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.pem
## Then in nginx.conf
lua_ssl_verify_depth 2;
lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.pem;
```

**Comment by fractos** [comment]
@steve-chavez Fantastic, thanks for that - worked perfectly.

**Comment by taf2** [comment]
what about when using resty on the command line?   

i tried like:
```
resty --main-conf 'lua_ssl_verify_depth 2;lua_ssl_trusted_certificate /usr/local/etc/openssl/cert.pem;'
```

but that gives 

```
nginx: [emerg] "lua_ssl_verify_depth" directive is not allowed here in /tmp/resty_KTiSmqiccD/conf/nginx.conf:110
```

**Comment by karl-chanel** [comment]
marked
