### ISSUE TITLE
basic auth

### ISSUE THREAD

**Issue by jney** [pintsized/lua-resty-http#48]
is there a way to pass basic auth credentials, or should i concatenate the string ?

**Comment by hamishforbes** [comment]
Yep just construct an Authorization header yourself and pass that into the headers table when you make a request.
Off the top of my head it should be something like

```lua
local authorization = 'Basic '..ngx.encode_base64(user..':'..pass)
```
https://github.com/openresty/lua-nginx-module#ngxencode_base64

**Comment by BlackGhostKing** [comment]
@hamishforbes  thank you
