### ISSUE TITLE
async call

### ISSUE THREAD

**Issue by jney** [pintsized/lua-resty-http#49]
is it possible to make a call without waiting for the response ?

**Comment by pintsized** [comment]
Yes, depending on what you mean. You can use the documented "generic interface" to send a request, and wait only for status / headers. The body wont be transferred until you utilise the `body_reader`.

If however you wish to initiate one or more requests and move on whilst they are being sent, you would need to use light threads, as documented here: https://github.com/openresty/lua-nginx-module#ngxthreadspawn

**Comment by jney** [comment]
you pointed me the good ressource, thank you
