### ISSUE TITLE
Saving an image on a file

### ISSUE THREAD

**Issue by CriztianiX** [pintsized/lua-resty-http#50]
I'm trying to save an image on a file.

```lua
local httpc = http.new()
local res, err = httpc:request_uri(path, {
  method = "GET",
  ssl_verify = false
})
if not res then
  return return_not_found()
end

local reader = res.body_reader
local f = assert(io.open('test.jpg', 'wb'))

repeat
  local chunk, err = reader(8192)
  if err then
    ngx.log(ngx.ERR, err)
    break
  end
  if chunk then
    print("Writing chunk to file...")
  end
until not chunk
f:close()
```

But i get the following error:
```bash
2016/02/22 21:12:18 [error] 9649#0: *1 [lua] server_image.lua:46: can't resume a dead coroutine, client: 192.168.1.13, server: , request: "GET /images/420x353/https://myhost.com/fondo-01.png HTTP/1.1", host: "192.168.1.241:19654"
```

**Comment by pintsized** [comment]
Can you post the response headers from your image? I'm wondering if there's an incorrect Content-Length or something like that? Either way, seeing the headers tells us which code paths are used (chunked encoding vs non-chunked etc). Does this happen straight away, or do you get some data first?

**Comment by CriztianiX** [comment]
Thanks for the reply!
The response headers:
```lua
{
    [Date] = "Tue, 23 Feb 2016 13:36:10 GMT"
    [Content-Type] = "image/png"
    [ETag] = ""c9b7e36a340337dc2debf0c3627c68de""
    [Last-Modified] = "Thu, 04 Feb 2016 19:33:04 GMT"
    [Server] = "AmazonS3"
    [Content-Length] = "46959"
    [x-amz-request-id] = "D63E929ADDF8FB95"
    [Accept-Ranges] = "bytes"
    [x-amz-id-2] = "Wira45TxzQD1BlIiESiC03G2O/4ov8RgS5auKpGcBeyngjyW0NBGNTdo99fIsyo9pC5IkKQ7W+U="
}
```

**Comment by pintsized** [comment]
Oh wait, I didn't read your example properly. You're using the `request_uri` syntax, which is for simplified cases where you don't wish to stream the response. So in your case, the body will have already been read into the `res.body` field by the time the call to `request_uri` has completed.

If you wish to stream, please follow the example docs for the "generic interface", where you must connect manually, and use the `request` method, before using the body reader.

**Comment by hamishforbes** [comment]
Maybe request_uri should reset body_reader to `_no_body_reader()` before returning?
`read_body()` should probably do this too

**Comment by pintsized** [comment]
Hmm, maybe. I mean, the error makes sense - the coroutine is dead and can no longer be resumed. Replacing it for a function that just returns `nil` seems like an unnecessary safety net? I reckon just some clearer documentation might be better :)

**Comment by CriztianiX** [comment]
Thanks! using "generic interface" it works!
