### ISSUE TITLE
SSL: client cert support

### ISSUE THREAD

**Issue by rohitjoshi** [pintsized/lua-resty-http#54]
Is there anyway to specify client certificate/key while connecting to backend/upstream server using SSL?

**Comment by hamishforbes** [comment]
Not at the moment. The underlying (ngx.socket.tcp)[https://github.com/openresty/lua-nginx-module#tcpsocksslhandshake] implementation doesn't support client certs.
When / If it does adding support to resty-http should be fairly easy.

**Comment by gitrus** [comment]
Still unavailable?

**Comment by codeb2cc** [comment]
If the upstream is not variable, try to define a proxy block and use Nginx's `proxy_ssl_certificate_key` and `proxy_ssl_certificate` as workaround.

**Comment by dwradcliffe** [comment]
FYI https://github.com/openresty/lua-nginx-module/pull/997
