### ISSUE TITLE
help need to https, curl -u command what should i do

### ISSUE THREAD

**Issue by BlackGhostKing** [pintsized/lua-resty-http#58]
i want to request https, 
curl --insecure -X POST -v https://xx.xx.xx -H "Content-Type: application/json" -u "121121212:121212121" -d "{xx:xx}"

curl -u  xxx:xxx command, and in resty. HTTP, what should I do

**Comment by hamishforbes** [comment]
Hey, you need to create the authorisation header manually, see #48

**Comment by BlackGhostKing** [comment]
hi hamishforbes,
i want to request https,error info [failed to request: 20: unable to get local issuer certificate ]what should i do,
The following code, 
local http = require "resty.http"
local httpc = http.new()
local authorization = 'Basic '..ngx.encode_base64("4a6b160baecafd0ae1971fc7:a52a32322323232d58475")
local resp, err = httpc:request_uri(SERVER, {
    method = "POST",
    body = pushCotent,
    ssl_verify=true,
    headers = { 
      ["Authenticate"] = authorization, 
      ["Content-Type"] = "application/json",     
    }
})

**Comment by guanglinlv** [comment]
you need to config your Root CA  using [lua_ssl_trusted_certificate](https://github.com/openresty/lua-nginx-module#lua_ssl_trusted_certificate) directive, see [#42](https://github.com/pintsized/lua-resty-http/issues/42).

**Comment by BlackGhostKing** [comment]
@guanglinlv  thank you

**Comment by pjg864** [comment]
@hamishforbes @guanglinlv   On Mac OS X 10+,  no need to configure lua_ssl_trusted_certificate, but on Ubuntu 14.04LTS, need to configure it, why?  is there any default ca file path used in openresty, or read from specific system ENV value?

**Comment by hamishforbes** [comment]
@pjg864 I don't know for sure, but afaik OS X uses a completely different SSL library so its not surprising there are differences. 

lua-resty-http just uses ngx_lua's SSL cosocket API which in turn depends upon the Nginx SSL functionality. So this isn't really related to resty-http at all.
The Openresty mailing list is probably more appropriate: https://groups.google.com/forum/?fromgroups=#!forum/openresty-en

**Comment by pjg864** [comment]
@hamishforbes Got it, thanks!
