### ISSUE TITLE
when timeout, got `lua tcp socket read timed out` and cannot catch it.

### ISSUE THREAD

**Issue by rrfeng** [pintsized/lua-resty-http#64]
I need retry a http request every 2 min, and timeout is ok, but I cannot prevent the nginx to log `lua tcp socket read timed out`.

Is there a way to make it?

**Comment by guanglinlv** [comment]
https://github.com/openresty/lua-nginx-module#lua_socket_log_errors

**Comment by rrfeng** [comment]
@guanglinlv Thanks! I got it.
