### ISSUE TITLE
Some url cannot parsed correctly.

### ISSUE THREAD

**Issue by prehawk1999** [pintsized/lua-resty-http#65]
Like http://www.google.com#30, chrome will extend as http://www.google.com/#30 and domain will be regconized.
But resty.http will regconized the domain as www.google.com#30,
There are more cases shows below
http://www.tencent.com\fh       
https://p.skimresources.com?provider_id=236e5777
these url can be correctly regconized by chrome, but not with resty.http.
if the regex is changed like: [[^(http[s]*)://([^:/\\\\#?]+)(?::(\d+))?(.*)]], this issue will be corrected.

**Comment by pintsized** [comment]
That URI is invalid though. Chrome may move the hash to somewhere valid for you, but that's just a browser trying to guess what you mean. Curl, for example will parse the host as `www.google.com#30`, and fail. I think the correct thing for us to do is fail if given an invalid URI.
