### ISSUE TITLE
How to request for https?

### ISSUE THREAD

**Issue by pronan** [pintsized/lua-resty-http#68]
```
        location / {
            resolver 8.8.8.8;
            content_by_lua_block {
    local client = require "resty.http":new()
    local res, err = client:request_uri('https://graph.qq.com/oauth2.0/token')
        }
```
Get err `unable to get local issuer certificate`

**Comment by pronan** [comment]
solved

**Comment by pronan** [comment]
```client:request_uri(url, {
        ssl_verify = false, 
    })```

**Comment by wenqibiao** [comment]
Anyway, how to specify a certificate?

**Comment by aditya730** [comment]
@wenqibiao @xiangnanscu Could you figure out how to specify a certificate in the request ?

**Comment by aditya730** [comment]
This solved the issue for me in docker run time environment.Should work for other run times as well.
https://github.com/pintsized/lua-resty-http/issues/42
