### ISSUE TITLE
Can this driver be used in the balancer_by_lua block?

### ISSUE THREAD

**Issue by tjliupeng** [pintsized/lua-resty-http#73]
Hi, 

Can lua-resty-http be used in the balancer block provided by https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md? 

In my application, I need to send HTTP request to backend server when doing load balance?

Thanks

**Comment by hamishforbes** [comment]
No. There are no TCP cosockets available in balancer_by_lua.

https://github.com/openresty/lua-nginx-module#balancer_by_lua_block

> This Lua code execution context does not support yielding, so Lua APIs that may yield (like cosockets and "light threads") are disabled in this context. One can usually work around this limitation by doing such operations in an earlier phase handler (like access_by_lua*) and passing along the result into this context via the ngx.ctx table.

https://github.com/openresty/lua-nginx-module#ngxsockettcp
> context: rewrite_by_lua*, access_by_lua*, content_by_lua*, ngx.timer.*, ssl_certificate_by_lua*, ssl_session_fetch_by_lua*

**Comment by tjliupeng** [comment]
So, any alternatives for that? I need to get some dynamic data from the upstream nodes for load balance.

**Comment by iriyak** [comment]
@hamishforbes 

Hi, I tried myself outside balancer_by_lua directive with no luck. Is that coming from the same reason that no TCP cosockets available?

What I did is adding the custom logic with resty.http to call within the entry point and pass along via ngx.ctx. But ngx mentions we attempted to send data on a closed socket as below. There was no HTTP connection established toward twitter.com in my example and ngx.ctx.val_from_httpclient remains nil.

```
2016/09/01 16:22:36 [debug] 10812#10900: *102 [lua] http.lua:568: send_request():
GET / HTTP/1.1
Host: twitter.com
User-Agent: lua-resty-http/0.09 (Lua) ngx_lua/10005

2016/09/01 16:22:36 [error] 10812#10900: *102 attempt to send data on a closed socket: u:017D0C48, c:00000000, ft:8 eof:0, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7082"
2016/09/01 16:22:36 [error] 10812#10900: *102 [lua] balancer_by_lua:6: -2 while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7082"
```
nginx.conf
```
    upstream backend {
        server 0.0.0.1;

        balancer_by_lua_block {
            local balancer = require "ngx.balancer"
            local host = "127.0.0.1"
            local port = 7083;

            ngx.log(ngx.ERR, ngx.ctx.val_from_httpclient)

            local ok, err = balancer.set_current_peer(host, port)
            if not ok then
                ngx.log(ngx.ERR, "failed to set the current peer: ", err)
                return ngx.exit(500)
            end
        }
        keepalive 10;
    }

    server {
        # entry point
        listen      7082;
        location / {
            rewrite_by_lua_file 'lualib/kiriya/t.lua';
            proxy_pass http://backend/fake;
        }
    }

    server {
        listen      7083;
        location /fake {
            return 200 "This is the fake backend peer...";
        }
    }
```

t.lua
```
ngx.ctx.val_from_httpclient = 0

local http = require "resty.http"
local httpc = http.new()

if not httpc then
	ngx.ctx.val_from_httpclient = -1
	ngx.log(ngx.ERR, "nil")
	return
end

httpc:set_timeout(30000)
httpc:connect("twitter.com", 80)

local res, err = httpc:request{
	method = "GET",
	path = "/",
}

if err then
	ngx.ctx.val_from_httpclient = -2
	return
end

if not res then
	ngx.ctx.val_from_httpclient = -3
	return
end

ngx.ctx.val_from_httpclient = 123
ngx.log(ngx.ERR, tostring(res.status))
```

**Comment by hamishforbes** [comment]
You haven't read the response, try using the request_uri method.
I'd suggest making sure your code in rewrite is doing what you expect it to before adding the balancer stuff, otherwise you're going to end up confusing the issue :)

That would seem to be the correct approach, I haven't actually used balancer_by_lua, we do all our proxying and load balancer in Lua rather than with the nginx proxy module.
That's the suggested solution to needing cosockets in balancer though.

**Comment by iriyak** [comment]
@hamishforbes 

Ah you're right, I haven't finished coding yet since the script has ended up with returning -2. As you suggested I will explore further and get back with you guys.
