### ISSUE TITLE
using 'ngx.var.request_uri ' instead of ngx_re_gsub(ngx_var.uri, "\\s", "%20", "jo") .. ngx_var.is_args .. (ngx_var.query_string or "")

### ISSUE THREAD

**Issue by perfgao** [pintsized/lua-resty-http#77]
Hi,

Can you consider using 'ngx.var.request_uri ' instead of ngx_re_gsub(ngx_var.uri, "\s", "%20", "jo") .. ngx_var.is_args .. (ngx_var.query_string or "") ?

function _M.proxy_request(self, chunksize)
    return self:request{
        method = ngx_req_get_method(),
        path = ngx_re_gsub(ngx_var.uri, "\s", "%20", "jo") .. ngx_var.is_args .. (ngx_var.query_string or ""),
        body = self:get_client_body_reader(chunksize),
        headers = ngx_req_get_headers(),
    }
end

**Comment by hamishforbes** [comment]
No, `request_uri` is always the unmodified original URI, including query strings.
Using this variable would result in unexpected behaviour whenever you modify the query string or URI before proxying the request.

e.g.

```
location /proxy/me {
    rewrite ^/proxy/me(.*) $1 break;
    content_by_lua_block {
       ... resty.http proxy code here ...
    }
}
```

A request for `/proxy/me/some/path` would be proxied to `/proxy/me/some/path` not the expected `/some/path` on the origin server.
