### ISSUE TITLE
simple post request does not work

### ISSUE THREAD

**Issue by wanghaisheng** [pintsized/lua-resty-http#78]
os:mac 

i am trying to build post request  using following code
```

      -- For simple singleshot requests, use the URI interface.
      local http = require "resty.http"
      local httpc = http.new()
      local res, err = httpc:request_uri("http://wi.hit.edu.cn/cemr", {
        method = "POST",
                headers = { ["Upgrade-Insecure-Requests"]="1",
                ["accept"]="text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",["Accept-Encoding"]="gzip, deflate",
                ["referer"]="http://wi.hit.edu.cn/cemr/",["cache-control"]="max-age=0",["connection"]="keep-alive",
                ["user-agent"]="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0",
                ["host"]="wi.hit.edu.cn",["Content-Length"]="705",["Content-Type"] = "application/x-www-form-urlencoded" },
                body = "source=1. 患者既往有高血压病史,最高达180/100mmHg,口服北京降压灵、利血平治疗,有脑梗死病史,遗留语笨及左侧肢体无力.2. 门诊行头CT检查,显示左侧侧脑室体旁低密度病灶,以脑梗死收入我科."

      })

      if not res then
        ngx.say("failed to request: ", err)
        return
      end

      -- In this simple form, there is no manual connection step, so the body is read
      -- all in one go, including any trailers, and the connection closed or keptalive
      -- for you.

      ngx.status = res.status

      for k,v in pairs(res.headers) do
          --
      end

      ngx.say(res.body)

```

outcome i am looking for is to realize post request in  the following  page 
http://wi.hit.edu.cn/cemr/,
the full request info i get from firefox debug tools is 
```
Host: wi.hit.edu.cn
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://wi.hit.edu.cn/cemr/
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0

form-data  
source:"1.+患者既往有高血压病史,最高达180/100mmHg,口服"北京降压灵、利血平"治疗,有脑梗死病史,遗留语笨及左侧肢体无力.
2.+门诊行头CT检查,显示左侧侧脑室体旁低密度病灶,以"脑梗死"收入我科."
```

full error is like this 
```
2016/09/19 21:51:58 [error] 28920#0: *31 lua tcp socket read timed out, client: 127.0.0.1, server: , request: "GET /cemr HTTP/1.1", host: "localhost:8081"

```

but curl works
curl -d "source=患者既往有高血压病史,最高达180/100mmHg,口服北京降压灵、 利血平治疗,有脑梗死病史,遗留语笨及左侧肢体无力." http://wi.hit.edu.cn/cemr/  > result.html

**Comment by pintsized** [comment]
>full error is like this

> 2016/09/19 21:51:58 [error] 28920#0: *31 lua tcp socket read timed out, client: 127.0.0.1, server: , request: "GET /cemr HTTP/1.1", host: "localhost:8081"

There's a fairly big hint there.

https://github.com/pintsized/lua-resty-http#set_timeout

**Comment by wanghaisheng** [comment]
after add 
```
      httpc:set_timeout(60000)

```
or
```
      httpc:set_timeout(600)
```
still the same error

**Comment by pintsized** [comment]
Well, either way, the problem is because your origin is not responding in time. Are you sure your `Content-Length` request header is correct? If you tell the origin to expect more data than you send, perhaps it's waiting for it?

If you don't specify a `Content-Length` it will be calculated for you - give that a try?

**Comment by wanghaisheng** [comment]
it works

**Comment by NithishReddy** [comment]
am also implementing lua_resty_http but content_by_lua code in nginx.conf is not working. can you help ??? @wanghaisheng

**Comment by wanghaisheng** [comment]
@NithishReddy simplest way  you should just keep the necessary header param and delete others you dont know how they works

**Comment by NithishReddy** [comment]
nginx.conf code :
Server {


lua_package_path "/usr/local/ngx_openresty-1.5.8.1/build/lua-resty-http/lib/?.lua;;";

location ~ /abc/ {

    content_by_lua '

  local http = require "resty.http"
  local httpc = http.new()
  local res, err = httpc:request_uri("https://example.com/national/DetailPage/test", {
    method = "POST",
    body = "a=1&b=2",
    headers = {
      ["Content-Type"] = "application/x-www-form-urlencoded",
    }
  })

  if not res then
    ngx.say("failed to request: ", err)
    return
  end

  ngx.status = res.status

  ngx.say(res.body)
';
  }
}

Note : https://example.com is development server


content_by_lua code is not executing ??

**Comment by wanghaisheng** [comment]
@NithishReddy  i  would recommend you  read the tutorial  carefully   over here  https://github.com/openresty/lua-nginx-module  you can use  keyword "content_by_lua"
and this  book for beginners https://github.com/moonbingbing/openresty-best-practices
