### ISSUE TITLE
Download file or get file content by POST request. ([lua] http.lua:766: request_uri(): unread data in buffer,)

### ISSUE THREAD

**Issue by shubenkov** [pintsized/lua-resty-http#79]
Hello.

Is it possible to download file or get file content by POST request of http resty engine?
I try to get file, but error happens.

```
    function obj:CertGet(login,sms)
    local www = require('lualib.http').new()
    return www:request_uri("http://127.0.0.1:8084/", {
                    method = "POST",
                    body = "usr=v.shubenkov&pwd=ProlBleat",
            headers = {["Content-Type"] = "application/x-www-form-urlencoded"}
                    }
                    )
    end
```

local responce,err = conn:CertGet("1","2")
  if err ~= nil then
    ngx.say(json.encode({status="OK",text="Error 1 "..err}));
    ngx.exit(ngx.HTTP_OK);
  end

body, err = responce:read_body()

  ngx.say(json.encode({status="OK",text="Error 2 "..err}));
  ngx.exit(ngx.HTTP_OK);

err = "can't resume a dead coroutine"

nginx.log: 

2016/09/21 17:04:02 [error] 25904#0: *55330 [lua] http.lua:766: request_uri(): unread data in buffer, client: , server: ..., request: "POST /authadmdata/ HTTP/1.1", host: "...", referrer: "https://.../"

Response headers:

{"Content-Disposition":"filename=v.shubenkov-169E3E5E0001000018F1.pfx","Connection":"keep-alive","Date":"Wed, 21 Sep 2016 15:30:05 GMT","Content-Type":"application\/octet-stream","Cache-Control":"private","Content-Length":"3492","Server":"nginx\/1.9.15","CRTSerial":"169E3E5E0001000018F1","X-Powered-By":["PHP\/5.3.28","ASP.NET"]}

**Comment by yangm97** [comment]
So, how did you fix?

**Comment by nammehra** [comment]
@shubenkov ,
How did you fix this issue?
