### ISSUE TITLE
Clear coonnection cache (cookies) for each new session or connection.

### ISSUE THREAD

**Issue by shubenkov** [pintsized/lua-resty-http#88]
Hello.

I faced with interesting problem. I use http resty setup to get cookie from remote server by cross login\password:

      function obj:PHPAuth(login,pass)

                local www = require('lualib.http').new()
                result,result_error =  www:request_uri("http://"..ip_php.."/irj/portal", {
                        method = "POST",
                        body = "dummy",
                        headers = {["Authorization"] = self.setAuth(login,pass)}
                })
end

It works well. For examle, in first session, I catch nessary cookie from ip_php.

After that, In second session, anybody else will try to do the same operation, he will knowingly
use wrong authorization data. He will enter to ip_php service successfuly by previos cookie, which I have gotten  in first session.

How can I initialize uniq connection for each new session.

Best regards

**Comment by pintsized** [comment]
At a guess, perhaps this is happening because your `result` and `result_error` variables are global?

https://github.com/openresty/lua-nginx-module#lua-variable-scope

**Comment by shubenkov** [comment]
Hello. You are right.
