### ISSUE TITLE
proxy_response fails (sometimes) for redirect responses

### ISSUE THREAD

**Issue by itapacket** [pintsized/lua-resty-http#89]
Hi,
When using proxy_response() for responses that use HTTP status 301/302 and the location header, sometimes the response headers are not emitted properly by openresty (even though the ngx.header table and ngx.status are updated correctly). This is possibly due to the way nginx treats the location header. 
In my limited testing, the issue seems to be resolved by detecting redirect responses and using ngx.redirect explicitly rather than regular response proxying. 

I suggest adding the following code inside proxy_response, after the regular header setting step and before the body echo step:
if 300 <= response.status and 400 > response.status and response.headers["Location"] then
    return ngx.redirect(response.headers["Location"], response.status)
end

Best regards,
Itamar

**Comment by pintsized** [comment]
Hi. Firstly, I do slightly regret adding the proxy_request / response functions. They are mostly intended as examples, so feel free to re-implement your own versions to handle anything more specific.

That said, there shouldn't be any problems with 301/302 statuses. Please post a complete yet minimal example to recreate and I'll take a closer look.

**Comment by lixianliang** [comment]
hi，not support response status 301 and 302 in request_uri() ?

**Comment by pintsized** [comment]
Personally, I see this library as being a pure HTTP protocol implementation for OpenResty cosockets. It's not a web browser or a high level client. If you wish to respond to a 301 by reading the `Location` header and making another request, you are free to do that in your implementations. I don't really see this being the specific responsibility of lua-resty-http. 

I am willing to be persuaded otherwise, but remember there's no sane way for the generic interface to support redirects - you'd usually have to close / keepalive the connection and re-connect since you've been given a new URI to request.

**Comment by itapacket** [comment]
I agree that following redirects and so on is not a reasonable behavior for the lua-resty-http library.
Having said that, I think that given the fact the library still offers the proxy_response function, it should work reliably for HTTP 3xx responses, which is not the case at the moment.
When using the sample code from the main documentation as the content_by_lua* phase for a location in an otherwise empty config:
`local http = require "resty.http"
local httpc = http.new()

httpc:set_timeout(500)
local ok, err = httpc:connect(HOST, PORT)

if not ok then
  ngx.log(ngx.ERR, err)
  return
end

httpc:set_timeout(2000)
httpc:proxy_response(httpc:proxy_request())
httpc:set_keepalive()`

And then requesting http://httpbin.org/redirect/6
Seems to fail (the status code is correct, but the Location header is not sent).

I suggest we add the 3 lines of code I listed in the original issue documentation and would happily write the patch if you like.

**Comment by pintsized** [comment]
This is odd, I just tested against my local OpenResty and I see the `Location` header as expected. Am I missing something? Or could something else in your configuration be interfering?

```
$ curl -v -H "Host: httpbin.org" "http://127.0.0.1/redirect/6"
* About to connect() to 127.0.0.1 port 80 (#0)
*   Trying 127.0.0.1... connected
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /redirect/6 HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Accept: */*
> Host: httpbin.org
>
< HTTP/1.1 302 Moved Temporarily
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Date: Wed, 16 Nov 2016 16:55:30 GMT
< Location: /relative-redirect/5
< Server: nginx
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
* Connection #0 to host 127.0.0.1 left intact
* Closing connection #0
<p>You should be redirected automatically to target URL: <a href="/relative-redirect/5">/relative-redirect/5</a>.  If not click the link.
```
