### ISSUE TITLE
how to send ngx.req.uri_args to backend server 

### ISSUE THREAD

**Issue by fankeke** [pintsized/lua-resty-http#91]
HI , If I want to send original request's uri args ,what shoud I do ? 
httpc:request( )   API does not have a `args` parameter ， So  I should put uri args to `path` ? 

Any tips would be appreciate .

**Comment by pintsized** [comment]
Yes, the URI args are supplied with the `path`. Take a look at the `proxy_request` method as an example (or just use this method directly if it suits): https://github.com/pintsized/lua-resty-http/blob/master/lib/resty/http.lua#L821

**Comment by fankeke** [comment]
I see. thanks and for your excellent work .
