### ISSUE TITLE
connection in dubious state?

### ISSUE THREAD

**Issue by zzctmac** [pintsized/lua-resty-http#94]
when I use request_uri to request a http url, i got this error.here  my code is:
```lua
_M.get = function(self, key)
    local httpc = http.new()
    local path = "/get?key=".. key;
    local api = string.format("http://%s:%s", self.host, self.port);
    local resp, err = httpc:request_uri(api, {
        method = "GET",
        path = path
    })
    if not resp then
        ngx.say("request error :", err)
        return nil;
    end
    if resp.status ~= 200 then
        return nil;
    end
    local content = resp.body;
    if(_M.prepare ~= nil) then
        content = _M.prepare.handle_one(content);
    end

    return content;

end
```

**Comment by pintsized** [comment]
Seems odd. Does the URI behave correctly using cUrl? On which line is that error triggered?

It's the sort of error you might get when trying to close / keepalive a socket, but there's still data to be read. For example, if the `Content-Length` response header doesn't match the actual data length?

If you have DEBUG level logging, you'll see the request that lua-resty-http is trying to make - please paste that here too.

**Comment by zzctmac** [comment]
request:
GET /get?key=2673389-3 HTTP/1.1
Host: 192.168.1.179:9133
User-Agent: lua-resty-http/0.09 (Lua) ngx_lua/10007

response:
HTTP/1.1 200 OK
Content-Length: 180
Server: xxx-server/0.1
Content-Type: text/plain

<t><![CDATA[XXX]]></t><u>http://item.jd.com/2673389.html</u><i>http://img14.360buyimg.com/n0/jfs/t2674/19/393419969/208299/4f604f38/57105d83N4dce4841.jpg</i><p></p><d>0</d><p>0</p>

**Comment by pintsized** [comment]
Again, does requesting the URI using `curl` work without errors? On which line do you receive the "connection in dubious state" error? Does `resp.body` contain the response body or not?

**Comment by zzctmac** [comment]
sorry, I forgot some detail.
curl works. the error was happened in http.lua:777 .resp.body contains full  response body.

**Comment by pintsized** [comment]
That's odd, line 777 should be a `pcall` around getting the request socket: https://github.com/pintsized/lua-resty-http/blob/v0.09/lib/resty/http.lua#L777

But you don't appear to be using the client body reader function, so I don't see how it could error there. Are you sure this error is generated from the snippet you've sent, and not from somewhere else?

**Comment by zzctmac** [comment]
....I used the old version ,the line is 809 [https://github.com/pintsized/lua-resty-http/blob/master/lib/resty/http.lua#L809](https://github.com/pintsized/lua-resty-http/blob/master/lib/resty/http.lua#L809)

**Comment by pintsized** [comment]
Ah yes, that makes more sense. In which case, it's a failure to place the socket in the keepalive pool for some reason. I'm fairly sure this is most likely because there's still some data left on the socket.

Is there any chance that your response body and `Content-Length` are not matched? Your example looks ok to me, but that's definitely the sort of thing that's going to cause this. With a `Content-Length` we read what we're told, and if there's still data to come, the socket wont be in a state that can be used in the keepalive pool.

Is there anything else special / particular about the server you are connecting to? It appears to be a custom server? Does it support keepalives?

The thing to keep in mind here is that everything is working fine, up until the point where we try to keepalive the connection.

**Comment by zzctmac** [comment]
The http server's provider tells me  he will close  the http connection  when data has been retuned and it does not support keepalives .so is it the key ?

**Comment by pintsized** [comment]
Ah yes, then your server is not complying to the specification: https://tools.ietf.org/html/rfc7230#section-6.1

> A server that does not support persistent connections MUST send the
   "close" connection option in every response message that does not
   have a 1xx (Informational) status code.

So to suppress this error your server provider needs to either:

1) Support keepalives
2) Set `Connection: close`

**Comment by zzctmac** [comment]
thanks.
