### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by claudiopetrini** [pintsized/lua-resty-http#96]
Hi,
I'm trying to proxy a request rewriting the host header before proxying it.
The code I'm using is the following : 
```lua
local http = require "resty.http"
local fiveMinutes = 300000
local poolSize = 100

local httpc = http.new()
httpc:set_timeout(5000)
httpc:connect("url.com", 80)

local res, err = httpc:request{
      path = '/',
      version = 1.1,
      headers = {
          ["Host"] = 'host.com'
      }
  }

if not res then
   ngx.say("not res failed to request: ", err)
   return
end

httpc:set_timeout(10000)
httpc:proxy_response(res)
  
local ok, err = httpc:set_keepalive(fiveMinutes, poolSize)
if not ok then
  ngx.say("failed to set keepalive: ", err)
  return
end
```

I'm not able to reproduce the error systematically but I sometimes get the error `recv() failed (104: Connection reset by peer)`.

**Comment by mirkods** [comment]
Hi @pintsized, i'm interested on it, do you have idea?

Cheers,
Mirko

**Comment by pintsized** [comment]
Hi Mirko,

I'm currently travelling for a few weeks and so don't have a computer with
me to look more closely. However, if the connection is being reset, that is
almost certainly something the server is doing.

If you suspect lua-resty-http isn't working correctly, try to recreate the
conditions using other tools to prove this.

My gut says this is something specific to your environment, and not likely
to be a bug. But without a computer it's hard for me to tell for sure.

James.

**Comment by pintsized** [comment]
Were you able to resolve this?

**Comment by claudiopetrini** [comment]
Hi @pintsized ,
I didn't manage to solve the issue but I discovered that this happens more frequently on bursty traffic, even if this isn't an high load.

I'm sorry but I'm still not able to give you an example to reproduce the issue systematically.

**Comment by qilifengxiang** [comment]
已经解决这个问题，把keep-alive关掉就好了

**Comment by pintsized** [comment]
Closing this as a "connection reset by peer" under high traffic is almost certainly expected server behaviour (i.e. not a client bug, but a server being restarted for example).

**Comment by decimalbell** [comment]
@claudiopetrini @qilifengxiang 
If you are using Nginx, see http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests
Nginx sets the maximum number of requests that can be served through one keep-alive connection, the default is 100 only.
