### ISSUE TITLE
some crashes due to null values in pcalls

### ISSUE THREAD

**Issue by ghost** [pintsized/lua-resty-http#97]
Am using lua-resty-openidc and some discovery paths don't return Connection nor Transfer-Encoding.  That causes the pcall(str_lower,...) calls to crash.  Temporarily wrote a custom def_pcall that takes as a third parameter a default value in case the original value is not defined. 

[http.lua.txt](https://github.com/pintsized/lua-resty-http/files/756282/http.lua.txt)

**Comment by pintsized** [comment]
Hi, sorry for the slow response. Are you able to submit a test proving this failure? I can't recreate it, so am most likely missing something specific about your case.
